# -*- coding: utf-8 -*-
"""LogicaRF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Df0qjErpobsflmIwWkve9JQo-fpH5t4x
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("CarPrice_Assignment.csv")
df["CarBrand"] = df["CarName"].apply(lambda x: x.split(" ")[0])
# novas features
df["avg_mpg"] = (df["citympg"] + df["highwaympg"]) / 2
df["power_per_engine"] = df["horsepower"] / df["enginesize"]
y = np.log1p(df["price"])
X = df.drop(columns=["price", "CarName"])
cat_features = X.select_dtypes(include="object").columns.tolist()
num_features = X.select_dtypes(exclude="object").columns.tolist()
print("Variáveis categóricas:", cat_features)
print("Variáveis numéricas:", num_features)
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_features)
    ]
)
feature_selector = SelectFromModel(
    RandomForestRegressor(
        n_estimators=300,
        max_depth=20,
        random_state=42,
        n_jobs=-1
    ),
    threshold="median"
)
model = RandomForestRegressor(
    n_estimators=500,
    max_depth=25,
    min_samples_split=3,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)
pipeline = Pipeline(
    steps=[
        ("preprocess", preprocessor),
        ("feature_selection", feature_selector),
        ("model", model)
    ]
)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)
pipeline.fit(X_train, y_train)
pred_log = pipeline.predict(X_test)
pred = np.expm1(pred_log)
y_test_real = np.expm1(y_test)
r2 = r2_score(y_test_real, pred)
mae = mean_absolute_error(y_test_real, pred)

print("\nRESULTADOS")
print(f"R²: {r2:.4f}")
print(f"MAE: {mae:.2f}")

def prever_carro(pipeline, **kwargs):
    df_input = pd.DataFrame([kwargs])
    for col in cat_features:
        if col in df_input.columns:
            df_input[col] = df_input[col].astype(str)
        else:
            df_input[col] = ""
    for col in num_features:
        if col in df_input.columns:
            df_input[col] = pd.to_numeric(df_input[col], errors="coerce")
        else:
            df_input[col] = 0.0
    pred_log = pipeline.predict(df_input)
    pred = np.expm1(pred_log)[0]
    return pred

preco = prever_carro(
    pipeline,
    symboling=1,
    wheelbase=95.7,
    carlength=180,
    carwidth=65,
    carheight=54,
    curbweight=2300,
    enginesize=150,
    boreratio=3.2,
    stroke=3.1,
    compressionratio=9,
    horsepower=120,
    peakrpm=5200,
    citympg=28,
    highwaympg=32,
    avg_mpg=30,
    power_per_engine=120/150,
    fueltype="gas",
    aspiration="std",
    doornumber="four",
    carbody="sedan",
    drivewheel="fwd",
    enginelocation="front",
    enginetype="ohc",
    cylindernumber="four",
    fuelsystem="mpfi",
    CarBrand="toyota"
)

print("Preço estimado:", preco)