# -*- coding: utf-8 -*-
"""RegressaoLinear

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyxZToq7pxtor_QkZrdogefPJnnPluX8
"""

import pandas as pd
from google.colab import files
#uploaded = files.upload()
df = pd.read_csv('CarPrice_Assignment.csv')
print(df)

!pip install -q streamlit

#import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

df_numerico = df.select_dtypes(include=['float64', 'int64'])
correlacao = df_numerico.corr()['price'].sort_values(ascending=False)
print("Ranking de Influência no Preço:")
print(correlacao)

def carregar_e_processar_dados(caminho_arquivo="CarPrice_Assignment.csv"):
    try:
        df = pd.read_csv(caminho_arquivo)
        colunas_usadas = ['enginesize', 'horsepower', 'highwaympg', 'citympg', 'drivewheel', 'price']
        df_modelo = df[colunas_usadas].copy()
        mapeamento_tracao = {'rwd': 0, 'fwd': 1, '4wd': 2}
        df_modelo['drivewheel'] = df_modelo['drivewheel'].map(mapeamento_tracao)

        return df_modelo, df
    except FileNotFoundError:
        return None, None

    return modelo, r2, mae

def treinar_modelo(df_modelo):
    X = df_modelo.drop('price', axis=1)
    y = df_modelo['price']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    modelo = LinearRegression()
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    return modelo, r2, mae

def prever_preco(modelo, motor, cavalos, consumo_estrada, consumo_cidade, tracao_valor):
    dados_input = pd.DataFrame([[motor, cavalos, consumo_estrada, consumo_cidade, tracao_valor]],
                             columns=['enginesize', 'horsepower', 'highwaympg', 'citympg', 'drivewheel'])
    return modelo.predict(dados_input)[0]

df_limpo, df_original = carregar_e_processar_dados()

if df_limpo is None:
    exit()

print("\n2. Treinando a Inteligência Artificial...")
modelo, r2, mae = treinar_modelo(df_limpo)

print(f"   Modelo treinado!")
print(f"   Precisão (R²): {r2:.2f}")
print(f"   Erro Médio: $ {mae:.2f}")

print("\n3. Simulando um carro para teste...")
motor = 120
cavalos = 100
consumo_estrada = 30
consumo_cidade = 25
tracao = 1

preco = prever_preco(modelo, motor, cavalos, consumo_estrada, consumo_cidade, tracao)

print(f"   O preço previsto para este carro é: $ {preco:,.2f}")